name: Run Pester Tests for AWS S3 Bucket

on:
  push:
    branches:
      - main  # Run tests on push to the main branch
  pull_request:
    branches:
      - main  # Run tests on pull requests targeting the main branch

jobs:
  run-pester-tests:
    runs-on: windows-latest  # Use a Windows runner to run PowerShell scripts

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS CLI using Chocolatey
      - name: Install AWS CLI using Chocolatey
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1')
          choco install awscli -y

      # Install the AWS PowerShell module
      - name: Install AWS PowerShell Module
        run: |
          Install-Module -Name AWSPowerShell -Force -Scope CurrentUser

      # Configure AWS credentials
      - name: Set up AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      # Install Pester module
      - name: Install Pester module
        run: |
          Install-Module -Name Pester -Force -Scope CurrentUser

      # Run the Pester tests and output to XML
      - name: Run Pester Tests
        run: |
          Invoke-Pester -Path ./tests/AwsS3.Tests.ps1 -OutputFormat NUnitXml -OutputFile ./test-results/test-results.xml

      # Ensure the XSLT file exists, and convert XML to HTML
      - name: Convert XML to HTML
        run: |
          # Define the XSLT and XML file paths
          $xsltPath = "./nunit-to-html.xslt"  # Update this path if the file is in a subfolder
          $xmlPath = "./test-results/test-results.xml"
          $htmlPath = "./test-results/test-results.html"

          # Check if XSLT file exists
          if (-Not (Test-Path $xsltPath)) {
            Write-Error "XSLT file not found at $xsltPath"
            exit 1
          }

          # Load XSLT and XML
          $xslt = New-Object System.Xml.Xsl.XslCompiledTransform
          $xslt.Load($xsltPath)

          # Load XML file and apply transformation
          $xml = New-Object System.Xml.XmlDocument
          $xml.Load($xmlPath)
          $xslt.Transform($xml, $null, [System.IO.StreamWriter]::new($htmlPath))

      # Install wkhtmltopdf using Chocolatey for converting HTML to PDF
      - name: Install wkhtmltopdf using Chocolatey
        run: |
          choco install wkhtmltopdf -y

      # Convert HTML to PDF using wkhtmltopdf
      - name: Convert HTML to PDF
        run: |
          wkhtmltopdf ./test-results/test-results.html ./test-results/test-results.pdf

      # Upload both HTML and PDF test results as artifacts
      - name: Upload test results (HTML and PDF)
        uses: actions/upload-artifact@v3
        with:
          name: pester-test-results
          path: |
            ./test-results/test-results.html
            ./test-results/test-results.pdf
