name: Run Pester Tests for AWS S3 Bucket

on:
  push:
    branches:
      - main  # Run tests on push to the main branch
  pull_request:
    branches:
      - main  # Run tests on pull requests targeting the main branch

jobs:
  run-pester-tests:
    runs-on: windows-latest  # Use a Windows runner to run PowerShell scripts

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS CLI using Chocolatey
      - name: Install AWS CLI using Chocolatey
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1')
          choco install awscli -y

      # Install the AWS PowerShell module
      - name: Install AWS PowerShell Module
        run: |
          Install-Module -Name AWSPowerShell -Force -Scope CurrentUser

      # Configure AWS credentials
      - name: Set up AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      # Install Pester module
      - name: Install Pester module
        run: |
          Install-Module -Name Pester -Force -Scope CurrentUser

      # Run the Pester tests without failing the pipeline
      - name: Run Pester Tests
        run: |
          # Run the Pester tests for AWS S3 and output to XML
          $results = Invoke-Pester -Path ./tests/AwsS3.Tests.ps1 -OutputFormat NUnitXml -OutputFile ./test-results/test-results.xml -PassThru
          if ($results.Passed -eq $false) {
              Write-Warning "Some tests failed. Continuing the build."
          }

      # Upload test results to GitHub Actions
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: pester-test-results
          path: ./test-results/test-results.xml
