name: Azure IQ Testing with Pester

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-pester-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: PowerShell/PowerShell@v7.2.1
        with:
          azPSSession: true 

      - name: Install Azure CLI
        run: |
          Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile ./azure-cli-installer.msi
          Start-Process msiexec.exe -ArgumentList '/i', './azure-cli-installer.msi', '/quiet', '/norestart' -NoNewWindow -Wait

      - name: Log in to Azure using Service Principal
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Install Pester module
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck

      - name: Run Pester Tests
        run: |
          # Path to the Pester test scripts
          Invoke-Pester -Script .\azure_tests\*.ps1
        shell: pwsh

      - name: Upload Pester Test Results as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pester-test-results
          path: ./azure_tests_output/*.xml  
